#! /bin/sh
#
# create_ubuntu_image.sh
# Copyright (C) 2016 mhristof <mhristof@orleans>
#
# Distributed under terms of the MIT license.
#

TMP="/tmp/ubuntu_iso_$(date +%s)"

while getopts "bi:hv" OPTION
do
     case $OPTION in
         b)
            vboxmanage createvm --name test01 --register --ostype Ubuntu_64
            vboxmanage modifyvm test01 --memory 256
            vboxmanage storagectl test01 --add ide --name IDE --portcount 2
            vboxmanage storagectl test01 --add sata --name SATA
            vboxmanage createmedium disk --size 8192 --filename ~/VirtualBox\ VMs/test01/root.vdi
            vboxmanage storageattach test01 --storagectl SATA --type hdd --medium ~/VirtualBox\ VMs/test01/root.vdi --port 0
            vboxmanage storageattach test01 --medium $IMAGE --storagectl IDE --port 0 --device 0 --type dvddrive
            exit 0;
            ;;

         i) IMAGE=$(readlink -f $OPTARG);;
         h)
            cat << EOF
 Creates a new iso for automated ubuntu installation
    arguments:
        -i ubuntu.iso       points to the ubuntu iso
EOF
             exit 1
             ;;
         v)
            VERBOSE=1;
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

mkdir $TMP
cd $TMP

echo $(pwd)
mkdir -p iso
mount -o loop $IMAGE iso
mkdir -p new_iso
cp -rT iso/ new_iso
cd new_iso
echo en >isolinux/lang
echo 'd-i partman/confirm_write_new_label boolean true
d-i partman/choose_partition \
    select Finish partitioning and write changes to disk
        d-i partman/confirm boolean true' > ks.preseed

password=$(cat ~/.ubuntu_image_password.txt)
cat << EOF > ks.cfg
#Generated by Kickstart Configurator
#platform=AMD64 or Intel EM64T

#System language
lang en_GB
#Language modules to install
langsupport en_GB
#System keyboard
keyboard gb
#System mouse
mouse
#System timezone
timezone Europe/London
#Root password
rootpw --disabled
#Initial user - generate password with 'printf "r00tme" | mkpasswd -s -m md5'
user mchristof --fullname "mchristof" --iscrypted --password $password 
#Reboot after installation
reboot
#Use text mode install
text
#Install OS instead of upgrade
install
#Use CDROM installation media
cdrom
#System bootloader configuration
bootloader --location=mbr 
#Clear the Master Boot Record
zerombr yes
#Partition clearing information
clearpart --all --initlabel 
#Disk partitioning information
part / --fstype ext4 --size 6000 
part swap --size 1000 
#System authorization infomation
auth  --useshadow  --enablemd5 
#Network information
network --bootproto=dhcp --device=eth0
#Firewall configuration
firewall --disabled 
#Do not configure the X Window System
skipx
%packages
@ ubuntu-server
openssh-server
python
EOF

sed -i -r 's/timeout\s+[0-9]+/timeout 1/g' isolinux/isolinux.cfg
perl -p -i -e 's!(append.*) --!$1 ks=cdrom:/ks.cfg preseed/file=/cdrom/ks.preseed noprompt --!' isolinux/txt.cfg 
mkisofs -D -r -V "ATTENDLESS_UBUNTU" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o $TMP/ubuntu.iso $TMP/new_iso

umount $TMP/iso
echo $(readlink -f $TMP/ubuntu.iso)

