#! /usr/bin/env python3
# vi: ft=python:

from sh import git
from sh import ErrorReturnCode_1

def main():
    """docstring for fname"""
    import argparse
    parser = argparse.ArgumentParser(description='Git commit wrapper')

    parser.add_argument('-a', '--all',
                        action='store_true',
                        help='Commit all messages')

    parser.add_argument('-u', '--undo-commit',
                        action='store_true',
                        help='Undo last commit, git reset HEAD~1')

    parser.add_argument('-m', '--message',
                        default=None,
                        help='Commit message')

    args, extra_args = parser.parse_known_args()

    if args.undo_commit:
        git.reset('HEAD~1')
        exit(0)
    if args.all:
        extra_args += ['-a']
    if args.message is not None:
        ticket = git('rev-parse', '--abbrev-ref', 'HEAD').split('/')[0]
        print('Adding ticket number', ticket, 'to commit message', args.message)
        if not ticket.startswith('master'):
            extra_args += ['-m', '{}: {}'.format(ticket, args.message)]
        else:
            extra_args += ['-m', args.message]

    print(git.commit(extra_args))
    

if __name__ == '__main__':
    main()


